---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: discovery-backend-spc
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "discovery-backend"
        objectType: "secretsmanager"
        jmesPath:
          - path: GOOGLE_API_KEY
            objectAlias: GOOGLE_API_KEY
          - path: DB_HOST
            objectAlias: DB_HOST
          - path: DB_PORT
            objectAlias: DB_PORT
          - path: DB_NAME
            objectAlias: DB_NAME
          - path: DB_USER
            objectAlias: DB_USER
          - path: DB_PASSWORD
            objectAlias: DB_PASSWORD
          - path: AWS_ACCESS_KEY_ID
            objectAlias: AWS_ACCESS_KEY_ID
          - path: AWS_SECRET_ACCESS_KEY
            objectAlias: AWS_SECRET_ACCESS_KEY
  secretObjects:
    - secretName: discovery-backend-secret
      type: Opaque
      data:
        - objectName: GOOGLE_API_KEY
          key: GOOGLE_API_KEY
        - objectName: DB_HOST
          key: DB_HOST
        - objectName: DB_PORT
          key: DB_PORT
        - objectName: DB_NAME
          key: DB_NAME
        - objectName: DB_USER
          key: DB_USER
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: AWS_ACCESS_KEY_ID
          key: AWS_ACCESS_KEY_ID
        - objectName: AWS_SECRET_ACCESS_KEY
          key: AWS_SECRET_ACCESS_KEY
---